#Verbose during prediction
verbose: False

img_size: 720
epochs: 200
batch_size: 8

#for training
mode: 'train'
data: "datasets/all_data/dataset.yaml"
output: "yolov8n_mot_ch"
model: weights/yolov8n.pt #download pretrained model on ultralytics
resume: False